<?php
$this->title = "Excluir Usuário";
$this->headTitle($this->title);
?>
<div class="container" style="margin-top:100px" />
<p>Tem certeza que deseja excluir o usuário 
 '<?php echo $this->escape($this->usuarios['nome']); ?>' ?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
 <input type="hidden" name="cpf" value="<?php echo $this->usuarios['cpf']; ?>" />
 <input type="submit" name="del" value="Sim" />
 <input type="submit" name="del" value="Não" />
</div>
</form>