<?php 
    $this->title = "Editar Cadastro";
    $this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Editar Cadastro</h2><br /> 

<div class="table">
    
    <form name="editUsuario" 
        action="<?php echo $this->url(array('controller'=>'usuario', 'action'=>'edit'));?>" 
        method="POST">
        
        <div class="form-group"> 
        <input type="hidden" name="cpf" class="form-control" value="<?php echo($this->usuarios['cpf']); ?>"/>
        </div>
        <div class="form-group">   
        <label>Nome: </label>
        <input type="text" name="nome" class="form-control" value="<?php echo($this->usuarios['nome']); ?>" required/>
        </div>
        <div class="form-group"> 
        <label>RG: </label>
        <input type="text" name="rg" class="form-control" value="<?php echo($this->usuarios['rg']); ?>" required/>
        </div>
        <div class="form-group"> 
        <label>Data Nasc: </label>
        <input type="date" name="dataNasc" class="form-control" value="<?php echo($this->usuarios['dataNasc']); ?>" required/>
        </div>
        <div class="form-group"> 
        <label>CEP: </label>
        <input type="text" name="cep" id="UsuarioCep" class="form-control" value="<?php echo($this->usuarios['cep']); ?>" maxlength="8" pattern="[0-9]+$" required/>
        </div>
        <div class="form-group"> 
        <label>Rua: </label>
        <input type="text" name="endereco" id="UsuarioEndereco" class="form-control" value="<?php echo($this->usuarios['endereco']); ?>" required/>
        </div>
        <div class="form-group"> 
        <label>Número: </label>
        <input type="text" name="numEndereco" class="form-control" value="<?php echo($this->usuarios['numEndereco']); ?>" required/>
        </div>
        <div class="form-group"> 
        <label>Bairro: </label>
        <input type="text" name="bairro" id="UsuarioBairro" class="form-control" value="<?php echo($this->usuarios['bairro']); ?>" required/>
        </div>
        <div class="form-group"> 
        <label>Cidade: </label>
        <input type="text" name="cidade" id="UsuarioCidade" class="form-control" value="<?php echo($this->usuarios['cidade']); ?>" required/>
        </div>
        <div class="form-group"> 
        <label>Estado: </label>
        <input type="text" name="estado" id="UsuarioUf" class="form-control" value="<?php echo($this->usuarios['estado']); ?>" required/>
        </div>

        <br /><p><h3>Suas informações de Login</h3></p>
        <div class="form-group"> 
        <label>Login: </label>
        <input type="text" name="login" class="form-control" value="<?php echo($this->auth['login']); ?>" maxlength="15" required/>
        </div>
        <div class="form-group">
        <label>Senha: </label>
        <input type="password" name="password" class="form-control" value="<?php echo($this->auth['pw']); ?>" required/>
        </div><br />
        
        <div class="form-group"> 
        <input type="submit" class="btn btn-default" value="Alterar"/>
        <input type="reset" class="btn btn-default" value="Limpar"/>
        </div>
    </form>
    
</div>