<?php 
$this->title = "Meu cadastro";
$this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Meu cadastro</h2>

<div class="row" style="margin-top:70px;margin-bottom:300px">
    <div class="col-md-4">
        <ul>
            <li><a href="<?php echo $this->url(array('controller'=>'usuario', 'action'=>'edit', 'cpf'=>$this->auth['userCpf']));?>">Alterar meus dados</a></li>
            <li><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'));?>">Ver jogos disponíveis</a></li>
            <li><a href="">Meus jogos</a></li>
            <li><a href="">Imprimir meu Ticket</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <p>
        Bem vindo! Aqui você pode alterar seus dados pessoais, login, senha, escolher os jogos que deseja assistir,
        além de ficar por dentro de todas as novidades em que estamos trabalhando. Selecione a opção desejada no menu
        ao lado!
        </p>
    </div>
</div>