<div style="margin-top:100px">
<?php if($this->msg != '') { ?>
<p><?php print_r($this->msg); } else { ?></p>
    <p>Parabéns! <br />
        Você foi sorteado! <br />
        Confira os dados do seu Jogo:
    </p>
    
<table class="table">
    <tr>
        <td>Código</td>
        <td><?php echo $this->jogos['id']; ?></td>
    </tr>    
    <tr>
        <td>Seleção 1</td>
        <td><?php echo $this->jogos['nomeTime1']; ?></td>
    </tr>    
    <tr>    
        <td>Seleção 2</td>
        <td><?php echo $this->jogos['nomeTime2']; ?></td>
    </tr>
    <tr>
        <td>Data</td>
        <td><?php echo $this->jogos['data']; ?></td>
    </tr>
    <tr>
        <td>Hora</td>
        <td><?php echo $this->jogos['hora']; ?></td>
    </tr>
    <tr>
        <td>Local</td>
        <td><?php echo $this->jogos['local']; ?></td>
    </tr>
    <tr>
        <td>Entradas disponíveis</td>
        <td><?php echo $this->jogos['vagas']; ?></td>
    </tr>
</table><br />
<?php } ?>
<p><a href="<?php echo $this->url(array('controller'=>'usuario', 'action'=>'pdf'));?>">Gerar meu Ticket</a></p>
<p><a href="<?php echo $this->url(array('controller'=>'usuario', 'action'=>'index'));?>">Retornar ao Painel</a></p>
</div>
