<?php 
    $this->title = "Novo Cadastro";
    $this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Novo Cadastro</h2><br />

<div class="table">
    
    <form name="novoUsuario" 
        action="<?php echo $this->url(array('controller'=>'usuario', 'action'=>'novo'));?>" 
        method="POST">
        
        <div class="form-group"> 
        <label>CPF: </label>
        <input type="text" name="cpf" class="form-control" placeholder="Digite seu CPF"/>
        </div>
        <div class="form-group">   
        <label>Nome: </label>
        <input type="text" name="nome" class="form-control" placeholder="Preencha seu nome completo"/>
        </div>
        <div class="form-group"> 
        <label>RG: </label>
        <input type="text" name="rg" class="form-control" placeholder="Digite seu RG"/>
        </div>
        <div class="form-group"> 
        <label>Data Nasc: </label>
        <input type="date" name="dataNasc" class="form-control" placeholder="Digite sua data de nascimento"/>
        </div>
        <div class="form-group"> 
        <label>CEP: </label>
        <input type="text" name="cep" id="UsuarioCep" class="form-control" placeholder="Digite seu CEP"/>
        </div>
        <div class="form-group"> 
        <label>Rua: </label>
        <input type="text" name="endereco" id="UsuarioEndereco" class="form-control" />
        </div>
        <div class="form-group"> 
        <label>Número: </label>
        <input type="text" name="numEndereco" class="form-control" placeholder="Digite o número de sua residência"/>
        </div>
        <div class="form-group"> 
        <label>Bairro: </label>
        <input type="text" name="bairro" id="UsuarioBairro" class="form-control" placeholder="Confira seu Bairro"/>
        </div>
        <div class="form-group"> 
        <label>Cidade: </label>
        <input type="text" name="cidade" id="UsuarioCidade" class="form-control" placeholder="Confira sua Cidade"/>
        </div>
        <div class="form-group"> 
        <label>Estado: </label>
        <input type="text" name="estado" id="UsuarioUf" class="form-control" placeholder="Confira seu Estado"/>
        </div>
        <br /><p><h3>Suas informações de Login</h3></p>
        <div class="form-group"> 
        <label>Login: </label>
        <input type="text" name="login" class="form-control" placeholder="O login deve ter no máximo 15 caracteres"/>
        </div>
        <div class="form-group">
        <label>Senha: </label>
        <input type="password" name="pw" class="form-control" placeholder="Sua senha deve ter entre 8 e 12 caracteres"/>
        </div><br />
        
        <div class="form-group"> 
        <input type="submit" class="btn btn-default" value="Enviar"/>
        <input type="reset" class="btn btn-default" value="Limpar"/>
        </div>
    </form>
    
</div>