<?php 
$this->title = "Sorteios Realizados";
$this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Sorteios Realizados</h2>

<table class="table">
    <tr>
        <th>Código</th>
        <th>Data</th>
        <th>Responsável</th>
        <th>Código do Jogo</th>
        <th>Documentos Sorteados</th>
    </tr>
    <?php foreach($this->sorteios as $sorteio) : ?>
    <tr>
        <td><?php echo $this->escape($sorteio->id); ?></td>
        <td><?php echo $this->escape($sorteio->data); ?></td>
        <td><?php echo $this->escape($sorteio->idResponsavel); ?></td>
        <td><?php echo $this->escape($sorteio->idJogo); ?></td>
        <td><?php echo $this->escape($sorteio->sorteados); ?></td>
    </tr>
    <?php endforeach; ?>
</table><br />
<p><a href="<?php echo $this->url(array('controller'=>'adm', 'action'=>'index'));?>">Retornar a Administração</a></p>