<?php 
    $this->title = "Editar Jogo";
    $this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Editar Jogo</h2><br /> 

<div class="table">
    
    <form name="editUsuario" 
        action="<?php echo $this->url(array('controller'=>'jogo', 'action'=>'edit'));?>" 
        method="POST">
        
        <div class="form-group"> 
        <input type="hidden" name="id" class="form-control" value="<?php echo($this->jogos['id']); ?>"/>
        </div>
        
        <div class="form-group">   
        <label>Seleção 1: </label>
        <select name="nomeTime1" class="form-control">
            <option value="<?php echo($this->jogos['nomeTime1']); ?>"><?php echo($this->jogos['nomeTime1']); ?></option>
            <?php foreach($this->times as $time) : ?>
                <option value="<?php echo $this->escape($time->nome);?>"><?php echo $this->escape($time->nome);?></option>
            <?php endforeach; ?>
        </select>   
        </div>
        
        <div class="form-group">   
        <label>Seleção 2: </label>
        <select name="nomeTime2" class="form-control">
            <option value="<?php echo($this->jogos['nomeTime2']); ?>"><?php echo($this->jogos['nomeTime2']); ?></option>
            <?php foreach($this->times as $time) : ?>
                <option value="<?php echo $this->escape($time->nome);?>"><?php echo $this->escape($time->nome);?></option>
            <?php endforeach; ?>
        </select>
        </div>
        
        <div class="form-group">   
        <label>Data do Jogo: </label>
        <input type="date" name="data" class="form-control" value="<?php echo($this->jogos['data']); ?>"/>
        </div>
        
        <div class="form-group">   
        <label>Horário: </label>
        <input type="time" name="hora" class="form-control" value="<?php echo($this->jogos['hora']); ?>"/>
        </div>
        
        <div class="form-group">   
        <label>Local: </label>
        <input type="text" name="local" class="form-control" value="<?php echo($this->jogos['local']); ?>"/>
        </div>
        
        <div class="form-group">   
        <label>Lugares Disponíveis: </label>
        <input type="text" name="vagas" class="form-control" value="<?php echo($this->jogos['vagas']); ?>"/>
        </div>
        
        <div class="form-group"> 
        <input type="submit" class="btn btn-default" value="Alterar"/>
        <input type="reset" class="btn btn-default" value="Limpar"/>
        </div>
    </form>
    
</div>