<?php 
$this->title = "Jogos Disponíveis";
$this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Jogos Disponíveis</h2>

<table class="table">
    <tr>
        <th>Código</th>
        <th>Seleção 1</th>
        <th>Seleção 2</th>
        <th>Data</th>
        <th>Hora</th>
        <th>Local</th>
        <th>Lugares Disponíveis</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <?php foreach($this->jogos as $jogo) : ?>
    <tr>
        <td><?php echo $this->escape($jogo->id); ?></td>
        <td><?php echo $this->escape($jogo->nomeTime1); ?></td>
        <td><?php echo $this->escape($jogo->nomeTime2); ?></td>
        <td><?php echo $this->escape($jogo->data); ?></td>
        <td><?php echo $this->escape($jogo->hora); ?></td>
        <td><?php echo $this->escape($jogo->local); ?></td>
        <td><?php echo $this->escape($jogo->vagas); ?></td>
        <td><a href="<?php echo $this->url(array('controller'=>'sorteio', 'action'=>'novo', 'idJogo'=>$this->escape($jogo->id)));?>">SORTEAR</a></td>
        <td><a href="<?php echo $this->url(array('controller'=>'jogo', 'action'=>'edit', 'id'=>$jogo->id));?>">Editar</a></td>
        <td><a href="<?php echo $this->url(array('controller'=>'jogo', 'action'=>'delete', 'id'=>$jogo->id));?>">Excluir</a></td>
    </tr>
    <?php endforeach; ?>
</table><br />