<?php 
    $this->title = "Novo Jogo";
    $this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Novo Jogo</h2><br />

<div class="table">
    
    <form name="novoJogo" 
        action="<?php echo $this->url(array('controller'=>'jogo', 'action'=>'novo'));?>" 
        method="POST">
        
        <div class="form-group">   
        <label>Seleção 1: </label>
        <select name="nomeTime1" class="form-control">
            <option value="0">Selecione o primeio País</option>
            <?php foreach($this->times as $time) : ?>
                <option value="<?php echo $this->escape($time->nome);?>"><?php echo $this->escape($time->nome);?></option>
            <?php endforeach; ?>
        </select>   
        </div>
        
        <div class="form-group">   
        <label>Seleção 2: </label>
        <select name="nomeTime2" class="form-control">
            <option value="0">Selecione o segundo País</option>
            <?php foreach($this->times as $time) : ?>
                <option value="<?php echo $this->escape($time->nome);?>"><?php echo $this->escape($time->nome);?></option>
            <?php endforeach; ?>
        </select>
        </div>
        
        <div class="form-group">   
        <label>Data do Jogo: </label>
        <input type="date" name="data" class="form-control" placeholder="Preencha a data do jogo"/>
        </div>
        
        <div class="form-group">   
        <label>Horário: </label>
        <input type="time" name="hora" class="form-control" placeholder="Preencha a hora de início da partida"/>
        </div>
        
        <div class="form-group">   
        <label>Local: </label>
        <input type="text" name="local" class="form-control" placeholder="Preencha o local da realização do jogo"/>
        </div>
        
        <div class="form-group">   
        <label>Lugares Disponíveis: </label>
        <input type="text" name="vagas" class="form-control" placeholder="Preencha a quantidade disponível de ingressos"/>
        </div>
        
        <div class="form-group"> 
        <input type="submit" class="btn btn-default" value="Enviar"/>
        <input type="reset" class="btn btn-default" value="Limpar"/>
        </div>
    </form>
    
</div>