<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle('Venda de ingressos'); ?>

        <!-- JS -->
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery-2.1.1.js'); ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/bootstrap.min.js'); ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/buscaCep.js'); ?>
        <?php echo $this->headScript(); ?>

        <!-- CSS -->
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/bootstrap.min.css', 'screen') ?>
        <?php echo $this->headLink(); ?>    
    </head>

    <body>

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'));?>">Venda de ingressos</a>
                </div>
                <ul class="nav navbar-nav">
                    <li></li>
                    <?php 
                        $log = Zend_Auth::getInstance();
                        $login = $log->getIdentity()->isAdm;
                        if ($login == 1) {
                    ?>
                        <li><a href="<?php echo $this->url(array('controller'=>'adm', 'action'=>'index'));?>">Administração</a></li>
                    <?php } else { ?>
                    <li><a href="<?php echo $this->url(array('controller'=>'usuario', 'action'=>'novo'));?>">Quero me cadastrar</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'jogo', 'action'=>'index'));?>">Jogos Disponíveis</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'usuario', 'action'=>'index'));?>">Meu Painel</a></li>
                    <?php } ?>
                </ul>
                <div class="navbar-collapse collapse">
                    <div class="navbar-brand navbar-right">
                        <?php echo $this->loggedInAs(); ?>
                    </div>
                </div><!--/.navbar-collapse -->
            </div>
        </div>

        <div class="container">
            <div class="content">
                <?php echo $this->layout()->content; ?>
            </div>

            <hr>

            <footer>
                <p>&copy; Evandro Morini 2014</p>
            </footer>
        </div> <!-- /container -->

    </body>
</html>
