<?php 
    $this->title = "Editar Seleção";
    $this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Editar Seleção</h2><br /> 

<div class="table">
    
    <form name="editUsuario" 
        action="<?php echo $this->url(array('controller'=>'time', 'action'=>'edit'));?>" 
        method="POST">
        
        <div class="form-group"> 
        <input type="hidden" name="id" class="form-control" value="<?php echo($this->times['id']); ?>"/>
        </div>
        <div class="form-group">   
        <label>Nome: </label>
        <input type="text" name="nome" class="form-control" value="<?php echo($this->times['nome']); ?>" required/>
        </div>
        
        <div class="form-group"> 
        <input type="submit" class="btn btn-default" value="Alterar"/>
        <input type="reset" class="btn btn-default" value="Limpar"/>
        </div>
    </form>
    
</div>