<?php 
$this->title = "Times";
$this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Times cadastrados</h2>

<table class="table">
    <tr>
        <th>Código</th>
        <th>Seleção</th>
        <th></th>
        <th></th>
    </tr>
    <?php foreach($this->times as $time) : ?>
    <tr>
        <td><?php echo $this->escape($time->id); ?></td>
        <td><?php echo $this->escape($time->nome); ?></td>
        <td><a href="<?php echo $this->url(array('controller'=>'time', 'action'=>'edit', 'id'=>$time->id));?>">Editar</a></td>
        <td><a href="<?php echo $this->url(array('controller'=>'time', 'action'=>'delete', 'id'=>$time->id));?>">Excluir</a></td>
    </tr>
    <?php endforeach; ?>
</table><br />