<?php 
    $this->title = "Nova Seleção";
    $this->headTitle($this->title);
?>

<h2 style="margin-top:100px">Nova Seleção</h2><br />

<div class="table">
    
    <form name="novoTime" 
        action="<?php echo $this->url(array('controller'=>'time', 'action'=>'novo'));?>" 
        method="POST">
        
        <div class="form-group">   
        <label>Nome: </label>
        <input type="text" name="nome" class="form-control" placeholder="Preencha o nome da seleção (apenas letras)" pattern="[a-z\s]+$" required/>
        </div>
        
        <div class="form-group"> 
        <input type="submit" class="btn btn-default" value="Enviar"/>
        <input type="reset" class="btn btn-default" value="Limpar"/>
        </div>
    </form>
    
</div>